/*
#	Java Les fondamentaux
#	A. Tasso
#	Carnet d'adresses
#	Fichier  : Contact.java
*/

package CarnetModele;

import IConsole.ES;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

// La classe Saisie hérite des comportements du composant JPanel
public class Contact extends javax.swing.JPanel {


    // Propriétés
	private Personne person;

    // Constructeur, les infos relatives à un contact sont passées en paramètre du constructeur
    // sous la forme d'un tableau (nom, prénom, ... et d'un identifiant
    public Contact(Personne person) {
        setVisible(true);
         // Afficher les composants créés en mode Design
        initComponents();
        // Initialiser les données
        this.person = person;
        // Colorier un contact sur deux en gris
        colorierIdPair();
        // Afficher les infos (la photo, le prénom et le nom)
        afficheInfos();

    }
	
    // Méthodes d'accès en écriture

	public void setPerson(Personne person) {
		this.person = person;
	}

	public void setNomLbl(JLabel nomLbl) {
		this.nomLbl = nomLbl;
	}

	public void setPhotoLbl(JLabel photoLbl) {
		this.photoLbl = photoLbl;
	}

	public void setPrenomLbl(JLabel prenomLbl) {
		this.prenomLbl = prenomLbl;
	}


    // Méthodes d'accès en lecture

	public Personne getPerson() {
		return person;
	}

	public JLabel getNomLbl() {
		return nomLbl;
	}

	public JLabel getPhotoLbl() {
		return photoLbl;
	}

	public JLabel getPrenomLbl() {
		return prenomLbl;
	}
	
    // Placer les nom, prénom et photo dans les labels respectifs
    private void afficheInfos(){
        prenomLbl.setText(person.getPrenom());
        nomLbl.setText(person.getNom());
        affichePhoto();
    }
    // Afficher la photo réduite du contact
    private void affichePhoto(){
        // Créer un icone
        ImageIcon iconPhoto = new ImageIcon(person.getNomPhoto());
        // Transformer l'icone en Image
        java.awt.Image uneImage = iconPhoto.getImage();
        // Réduire la taille de l'image de 50 %
        uneImage = uneImage.getScaledInstance(50, 50, java.awt.Image.SCALE_SMOOTH);
        // Transformer l'image en Icon
        iconPhoto.setImage(uneImage);
        photoLbl.setIcon(iconPhoto);
    }
	
    // Colorier en Blanc un label passé en paramètre
    private void setCouleur(javax.swing.JLabel tmp ){
                  tmp.setBackground(Color.white);
                  tmp.setOpaque(true);
     }

    private void colorierIdPair(){
        // Si l'id du contact est pair
        if(person.getId() % 2 == 0){
            setCouleur(nomLbl);
            setCouleur(prenomLbl);
            setCouleur(photoLbl);
        }
    }

	@Override
	public String toString() {
		return "Contact{ " + person.toString() +"}";
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photoLbl = new javax.swing.JLabel();
        prenomLbl = new javax.swing.JLabel();
        nomLbl = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(300, 50));
        setMinimumSize(new java.awt.Dimension(300, 50));
        setPreferredSize(new java.awt.Dimension(300, 60));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.GridLayout(1, 3));

        photoLbl.setMaximumSize(new java.awt.Dimension(10, 10));
        photoLbl.setPreferredSize(new java.awt.Dimension(10, 10));
        add(photoLbl);

        prenomLbl.setText("prénom");
        prenomLbl.setMaximumSize(new java.awt.Dimension(60, 40));
        prenomLbl.setMinimumSize(new java.awt.Dimension(60, 40));
        prenomLbl.setPreferredSize(new java.awt.Dimension(60, 40));
        add(prenomLbl);

        nomLbl.setText("nom");
        nomLbl.setMaximumSize(new java.awt.Dimension(40, 40));
        nomLbl.setMinimumSize(new java.awt.Dimension(40, 40));
        nomLbl.setPreferredSize(new java.awt.Dimension(40, 40));
        add(nomLbl);
    }// </editor-fold>//GEN-END:initComponents
    // Déclaration de variables créées par NetBeans par l'intermédiaire du mode Design
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nomLbl;
    private javax.swing.JLabel photoLbl;
    private javax.swing.JLabel prenomLbl;
    // End of variables declaration//GEN-END:variables

}
