/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarnetModele;

import Connexions.AccesFichier;
import IConsole.ES;
import java.awt.Color;
import java.awt.Dimension;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.Border;

/**
 *
 * @author alain
 */
public class MainFenetre3 extends javax.swing.JFrame {

	/**
	 * Creates new form MainFenetre3
	 */
	
	private TabPersonnes listePersonnes = new TabPersonnes();
	private ArrayList<Contact> listeContacts = new ArrayList<>();	
	private Border cadre;
	private int id = 0;
	private int numeroPrec = 0;
	private Saisie saisieDialog ;	
		
	public MainFenetre3() {
		initComponents();

		cadre = BorderFactory.createLineBorder(Color.orange);
		this.listePersonnes = initContacts("Donnees/listeContacts.txt");
		peupleContacts(boiteContacts);
		
		boiteInfos.add(new Infos(listePersonnes.retourner(1))) ;
		listeContacts.get(0).setBorder(cadre);
		listeContacts.get(numeroPrec).setBorder(null);		
		boiteInfos.validate();
	}
	
	private TabPersonnes initContacts(String fic){
		//int id=0;
		TabPersonnes tp = new TabPersonnes();
		String[] info = new String[8];
		AccesFichier ac = new AccesFichier(fic);
		ArrayList<String> al = null;
		try {
			al = ac.lireArray();
		} catch (IOException ex) {
			Logger.getLogger(MainFenetre2.class.getName()).log(Level.SEVERE, null, ex);
		}
		for (String st : al){
			id++;
			info = ac.extraireDonnees(st);
			Personne p = new Personne(id, info);
			tp.ajouter(p);
		}
		return tp;
	}

	private void peupleContacts(JPanel boiteContacts){
		// peuplement de la boiteContacts
		Dimension taille;
		for (int i=1; i<=listePersonnes.taille(); i++){
			Contact c = new Contact(listePersonnes.retourner(i));
			taille = c.getPreferredSize();
			c.setBounds(0, (i-1)*(taille.height+2), taille.width, taille.height);
			boiteContacts.add(c);
			taille.setSize(taille.width, (i+1)*(taille.height+2));
			boiteContacts.setPreferredSize(taille);
			boiteContacts.validate();
			ES.affiche(boiteContacts.getComponentCount()+"\n");
			
			listeContacts.add(c);
			listeContacts.get(i-1).addMouseListener(new java.awt.event.MouseAdapter() {
				@Override
				public void mouseReleased(java.awt.event.MouseEvent evt){
					contactMouseEvent(evt);
				}
			});
		}
	}
		
	private void contactMouseEvent(java.awt.event.MouseEvent evt) {
		Contact contactSelectionne = (Contact) evt.getSource();
		id = contactSelectionne.getPerson().getId();
		boiteInfos.removeAll();
		boiteInfos.add(new Infos(listePersonnes.retourner(id))) ;
		contactSelectionne.setBorder(cadre);
		listeContacts.get(numeroPrec).setBorder(null);
		numeroPrec = id-1;
		boiteInfos.validate();
		ES.affiche("\n");
	}
	
	private void plusBtnActionPerformed(java.awt.event.ActionEvent evt){
		saisieDialog = new Saisie(this, true);
		saisieDialog.setVisible(true);
		
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        boiteGlobale = new javax.swing.JPanel();
        boiteContacts = new javax.swing.JPanel();
        boiteInfos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        boiteGlobale.setLayout(new java.awt.GridLayout(1, 2));

        javax.swing.GroupLayout boiteContactsLayout = new javax.swing.GroupLayout(boiteContacts);
        boiteContacts.setLayout(boiteContactsLayout);
        boiteContactsLayout.setHorizontalGroup(
            boiteContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );
        boiteContactsLayout.setVerticalGroup(
            boiteContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        boiteGlobale.add(boiteContacts);

        boiteInfos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Infos"));

        javax.swing.GroupLayout boiteInfosLayout = new javax.swing.GroupLayout(boiteInfos);
        boiteInfos.setLayout(boiteInfosLayout);
        boiteInfosLayout.setHorizontalGroup(
            boiteInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );
        boiteInfosLayout.setVerticalGroup(
            boiteInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        boiteGlobale.add(boiteInfos);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boiteGlobale, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(boiteGlobale, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainFenetre3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainFenetre3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainFenetre3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainFenetre3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFenetre3().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boiteContacts;
    private javax.swing.JPanel boiteGlobale;
    private javax.swing.JPanel boiteInfos;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
