/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarnetModele;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

import IConsole.ES;

/**
 *
 * @author alain
 */
public class Saisie extends javax.swing.JDialog {

	private static final long serialVersionUID = 1L;

	private TabPersonnes listePersonnes;
	private Personne personne = new Personne();
	private String url = "Photos/photo0.png";
	private String fichier = "Donnees/listeContacts.txt";
	
	/**
	 * Creates new form Saisie
	 * @param listePersonnes 
	 */
	public Saisie(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		this.listePersonnes = ControleAdresse.lirePersonnes(fichier);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPhoto = new javax.swing.JLabel();
        lblPhoto.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseReleased(MouseEvent evt) {
        		recupererPhoto(evt);
        	}
        });
        txtPrenom = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTelDom = new javax.swing.JTextField();
        txtTelMob = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAdresse = new javax.swing.JTextField();
        txtCodePostalVille = new javax.swing.JTextField();
        btnValider = new javax.swing.JButton();
        btnValider.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		ajoutPersonne();
        	}
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ressources/modifier.png"))); // NOI18N
        lblPhoto.setText("jLabel1");

        txtPrenom.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        txtPrenom.setText("prénom");

        txtNom.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        txtNom.setText("nom");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Téléphones");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel2.setText("domicile");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel3.setText("portable");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("email");

        txtTelDom.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        txtTelDom.setText("votre numéro");

        txtTelMob.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        txtTelMob.setText("votre numéro");

        txtEmail.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        txtEmail.setText("prenom.nom@fai.fr");

        jLabel5.setText("Adresse");

        txtAdresse.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        txtAdresse.setText("numéro - rue");

        txtCodePostalVille.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        txtCodePostalVille.setText("code postal - ville");

        btnValider.setText("Valider");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNom)
                                    .addComponent(txtPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodePostalVille)
                                    .addComponent(txtTelMob)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(txtTelDom)
                                    .addComponent(txtAdresse)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(btnValider)))
                .addGap(0, 83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTelDom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTelMob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtCodePostalVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnValider)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void recupererPhoto(MouseEvent evt) {
		String nomFichier = "J:/Users/alain/Documents/Eclipse_java_serveur/CarnetAdresses/Photos/photo0.png";
    	File fichierPhoto = new File(nomFichier);
		JFileChooser ficherARechercher = new JFileChooser();
		ficherARechercher.setSelectedFile(fichierPhoto);
		int etatRetour = ficherARechercher.showOpenDialog(Saisie.this);
		if (etatRetour == JFileChooser.APPROVE_OPTION) {
			fichierPhoto = ficherARechercher.getSelectedFile();
			url = fichierPhoto.toString();
		}
		setPhoto(url);
	}

	private void ajoutPersonne() {
		validerPersonne();
		listePersonnes.ajouter(personne);
		ControleAdresse.ecrirePersonnes(listePersonnes, fichier);
		dispose();
	}
	
	public void supprimer(int id) {
		listePersonnes.supprimer(id-1);
		ControleAdresse.ecrirePersonnes(listePersonnes, fichier);
	}
	
    protected void validerPersonne() {
		personne.setNom(txtNom.getText());
		personne.setPrenom(txtPrenom.getText());
		personne.setTelDom(txtTelDom.getText());
		personne.setTelMob(txtTelMob.getText());
		personne.setEmail(txtEmail.getText());
		personne.setAdresse(txtAdresse.getText());
		personne.setVille(txtCodePostalVille.getText());
		personne.setNomPhoto(url);
		ES.affiche(url+"\n");
		ES.affiche(personne.toString()+"\n");
	}

	private void setPhoto(String strUrl) {
		ImageIcon iconPhoto = new ImageIcon(strUrl);
		lblPhoto.setIcon(iconPhoto);
	}
	
	public boolean getDonnees() {
		return true;
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Saisie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Saisie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Saisie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Saisie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				Saisie dialog = new Saisie(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnValider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtTelDom;
    private javax.swing.JTextField txtTelMob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtAdresse;
    private javax.swing.JTextField txtCodePostalVille;
    private javax.swing.JLabel lblPhoto;
    // End of variables declaration//GEN-END:variables
}
